apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: frigate-helm-values
  namespace: default
spec:
  keys:
    - values.yaml
  path: secrets/default/frigate/frigate-helm-values
  type: Opaque
