---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/gateway.envoyproxy.io/backend_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  name: unifi
  namespace: default
spec:
  endpoints:
    - fqdn:
        hostname: unifi.default.svc.cluster.local
        port: 8443
  tls:
    insecureSkipVerify: true
