---
# yaml-language-server: $schema=https://crd.movishell.pl/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-gcp-sa
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-assistant-gcp-sa-secret
    creationPolicy: Owner
  data:
  - secretKey: home-assistant-7c48d-46b62166197f.json
    remoteRef:
      key: home-assistant-gcp-sa
      property: home-assistant-7c48d-46b62166197f.json
