---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-gcp-sa
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: home-assistant-gcp-sa-secret
    creationPolicy: Owner
  data:
  - secretKey: home-assistant-7c48d-e078848c9fb0.json
    remoteRef:
      key: home-assistant-gcp-sa
      property: home-assistant-7c48d-e078848c9fb0.json
