createCRD: true
git:
  ssh:
    secretName: flux-git-deploy
chartsSyncInterval: "10m"
statusUpdateInterval: "10m"
prometheus:
  enabled: true
  serviceMonitor:
    create: true
    interval: 30s
    scrapeTimeout: 10s
    namespace: flux
