---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-test
spec:
  acme:
    email: jeff@billimek.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-test
    solvers:
    # An empty 'selector' means that this solver matches all domains
    - selector: {}
      dns01:
        cloudflare:
          email: jeff@billimek.com
          apiKeySecretRef:
            name: cloudflare-api-key
            key: api-key
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: jeff@billimek.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    # An empty 'selector' means that this solver matches all domains
    - selector: {}
      dns01:
        cloudflare:
          email: jeff@billimek.com
          apiKeySecretRef:
            name: cloudflare-api-key
            key: api-key
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: acme-crt
  namespace: cert-manager
spec:
  secretName: acme-crt-secret
  issuerRef:
    name: letsencrypt-test # TODO: change to letsencrypt-prod once old cluster is decommissioned
    kind: ClusterIssuer
  dnsNames:
  - eviljungle.com
  - '*.eviljungle.com'
  - '*.t.eviljungle.com'
