---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/httproute_v1.json
# TEMPORARY TEST ROUTE - DELETE AFTER VALIDATION
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: test-gateway-external
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/internal: "true"
    external-dns.alpha.kubernetes.io/target: "10.0.6.151"
    external-dns.alpha.kubernetes.io/external: "true"
spec:
  parentRefs:
    - name: external
      namespace: kube-system
      sectionName: https
  hostnames:
    - test-gateway.eviljungle.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: echo-server
          port: 8080
