---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: grafana-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # Grafana
        GF_DATABASE_USER: "{{ .GF_DATABASE_USER }}"
        GF_DATABASE_PASSWORD: "{{ .GF_DATABASE_PASSWORD }}"
        GF_DATABASE_HOST: postgres-v15-rw.default.svc.cluster.local:5432
        GF_DATABASE_NAME: grafana
        GF_DATABASE_SSL_MODE: disable
        GF_DATABASE_TYPE: postgres
        GF_AUTH_AZUREAD_CLIENT_ID: "{{ .AZURE_GRAFANA_CLIENT_ID }}"
        GF_AUTH_AZUREAD_CLIENT_SECRET: "{{ .AZURE_GRAFANA_CLIENT_SECRET }}"
        GF_AUTH_AZUREAD_AUTH_URL: "{{ .AZURE_AUTH_URL }}"
        GF_AUTH_AZUREAD_TOKEN_URL: "{{ .AZURE_TOKEN_URL }}"
        TESLAMATE_DB_PASSWORD: "{{ .TESLAMATE_POSTGRES_PASS }}"
        # Postgres Init
        POSTGRES_DB: grafana
        POSTGRES_HOST: postgres-v15-rw.default.svc.cluster.local
        POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_PASS: "{{ .GF_DATABASE_PASSWORD }}"
        POSTGRES_USER: "{{ .GF_DATABASE_USER }}"
  dataFrom:
    - extract:
        key: grafana
    - extract:
        key: teslamate
    - extract:
        key: cloudnative-pg
