apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: zwave2mqtt-helm-values
  namespace: default
spec:
  keys:
    - values.yaml
  path: secrets/default/zwave2mqtt/zwave2mqtt-helm-values
  type: Opaque
