---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: monica-helm-values
  namespace: default
spec:
  keys:
    - values.yaml
  path: secrets/default/monica/monica-helm-values
  type: Opaque
