apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: traefik-helm-values
  namespace: kube-system
spec:
  keys:
    - values.yaml
  path: secrets/kube-system/traefik/traefik-helm-values
  type: Opaque
