---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: true
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~1
spec:
  releaseName: traefik
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: traefik
    version: 1.77.0
  values:
    image: traefik
    imageTag: 1.7.14
    serviceType: LoadBalancer
    externalTrafficPolicy: Local
    loadBalancerIP: 10.2.0.150
    # loadBalancerIP: 10.2.0.210 # <-- k3s
    replicas: 2
    debug:
      enabled: false
    rbac:
      enabled: true
    ssl:
      enabled: true
      enforced: true
      insecureSkipVerify: true
      upstream: false
    gzip:
      enabled: false
    dashboard:
      enabled: true
      statistics:
        recentErrors: 25
    deployment:
      hostPort:
        dashboardEnabled: true
    metrics:
      prometheus:
        enabled: true
      serviceMonitor:
        enabled: true
        namespace: monitoring
        interval: 30s
    tolerations:
    - key: "arm"
      operator: "Exists"
  valueFileSecrets:
  - name: "traefik-helm-values"
