---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sonarr-restic
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sonarr-restic-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: '{{ .REPOSITORY_TEMPLATE }}/sonarr'
        RESTIC_PASSWORD: '{{ .RESTIC_PASSWORD }}'
        AWS_ACCESS_KEY_ID: '{{ .MINIO_ACCESS_KEY }}'
        AWS_SECRET_ACCESS_KEY: '{{ .MINIO_SECRET_KEY }}'
  dataFrom:
    - extract:
        key: minio
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: sonarr
  namespace: default
spec:
  sourcePVC: sonarr-config
  trigger:
    schedule: "50 6 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: sonarr-restic-secret
    cacheCapacity: 2Gi
    volumeSnapshotClassName: csi-rbdplugin-snapclass
    storageClassName: rook-ceph-block
    moverSecurityContext:
      runAsUser: 1001
      runAsGroup: 1001
      fsGroup: 1001
    retain:
      daily: 10
      within: 3d
