apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: thanos-helm-values
  namespace: monitoring
spec:
  keys:
    - values.yaml
  path: secrets/monitoring/thanos/thanos-helm-values
  type: Opaque
