---
# yaml-language-server: $schema=https://kube-schemas.pages.dev/monitoring.coreos.com/servicemonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kubernetes-event-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: kubernetes-event-exporter
    app.kubernetes.io/instance: kubernetes-event-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kubernetes-event-exporter
      app.kubernetes.io/instance: kubernetes-event-exporter
  endpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
      path: /metrics
