---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/nfd.k8s-sigs.io/nodefeaturerule_v1alpha1.json
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: intel-gpu-kabylake
spec:
  rules:
    - # Intel Kaby Lake HD 630 (Gen 9.5)
      name: intel.gpu.kabylake
      labels:
        intel.feature.node.kubernetes.io/gpu-gen: "9.5"
        intel.feature.node.kubernetes.io/gpu-family: "kabylake"
      matchFeatures:
        - feature: pci.device
          matchExpressions:
            class: {op: In, value: ["0300", "0380"]}
            vendor: {op: In, value: ["8086"]}
            device: {op: In, value: ["5912", "591b", "591d"]}
