apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-proxmox
  namespace: default
  labels:
    app.kubernetes.io/name: proxmox
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800s"
spec:
  ingressClassName: nginx-tailscale
  rules:
  - host: &host proxmox.eviljungle.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-proxmox
            port:
              number: 8006
  tls:
  - hosts:
    - *host
---
apiVersion: v1
kind: Service
metadata:
  name: external-proxmox
  namespace: default
spec:
  ports:
  - name: proxmox
    port: 8006
    targetPort: 8006
  type: ExternalName
  externalName: nas.home