---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    flux.weave.works/ignore: "false"
    flux.weave.works/automated: "false"
    flux.weave.works/tag.chart-image: semver:~1
spec:
  releaseName: traefik
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: traefik
    version: 1.69.1
  values:
    image: traefik
    imageTag: 1.7.12
    serviceType: LoadBalancer
    externalTrafficPolicy: Local
    loadBalancerIP: 10.2.0.150
    replicas: 2
    # startupArguments:
    # - --ping
    debug:
      enabled: false
    rbac:
      enabled: true
    ssl:
      enabled: true
      enforced: true
      insecureSkipVerify: true
      upstream: false
    dashboard:
      enabled: true
      statistics:
        recentErrors: 25
    deployment:
      hostPort:
        dashboardEnabled: true
  valueFileSecrets:
  - name: "traefik-values"

