apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: emqx-helm-values
  namespace: default
spec:
  keys:
    - values.yaml
  path: secrets/default/emqx/emqx-helm-values
  type: Opaque
