apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: oauth2-proxy-helm-values
  namespace: kube-system
spec:
  keys:
    - values.yaml
  path: secrets/kube-system/oauth2-proxy/oauth2-proxy-helm-values
  type: Opaque
