---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  browse-pvc:
    desc: Mount a PVC to an temp container [NS=default] [CLAIM=required]
    interactive: true
    cmd: kubectl browse-pvc --namespace {{.NS}} --image mirror.gcr.io/alpine:latest {{.CLAIM}}
    vars:
      NS: '{{.NS | default "default"}}'
    requires:
      vars: [CLAIM]
    preconditions:
      - kubectl --namespace {{.NS}} get persistentvolumeclaims {{.CLAIM}}
      - kubectl browse-pvc --version
      - which kubectl

  node-shell:
    desc: Open a shell to a node [NODE=required]
    interactive: true
    requires:
      vars: [NODE]
    preconditions:
      - kubectl get nodes {{.NODE}}
      - which kubectl
    cmds:
      - kubectl debug node/{{.NODE}} --namespace default --image=mirror.gcr.io/alpine:latest --profile=sysadmin -it
      - defer: kubectl delete pod --namespace default --selector app.kubernetes.io/managed-by=kubectl-debug --ignore-not-found=true

  sync-secrets:
    desc: Sync all ExternalSecrets
    cmds:
      - for: { var: SECRETS, split: "\n" }
        cmd: kubectl --namespace {{splitList "," .ITEM | first}} annotate externalsecret {{splitList "," .ITEM | last}} force-sync="{{now | unixEpoch}}" --overwrite
    vars:
      SECRETS:
        sh: kubectl get externalsecret --all-namespaces --no-headers --output=jsonpath='{range .items[*]}{.metadata.namespace},{.metadata.name}{"\n"}{end}'
    preconditions:
      - which kubectl

  cleanse-pods:
    desc: Cleanse pods with a Failed/Pending/Succeeded phase
    cmds:
      - for:
          matrix:
            PHASE: [Failed, Pending, Succeeded]
        cmd: kubectl delete pods --all-namespaces --field-selector status.phase={{.ITEM.PHASE}} --ignore-not-found=true
    preconditions:
      - which kubectl

  suspend-flux:
    desc: Suspend flux kusomization for cluster-apps
    preconditions:
      - which flux
    cmd: flux --namespace flux-system suspend kustomization cluster-apps

  resume-flux:
    desc: Resume flux kusomization for cluster-apps
    preconditions:
      - which flux
    cmd: flux --namespace flux-system resume kustomization cluster-apps

  keda-suspend:
    desc: Suspend all KEDA ScaledObjects across all namespaces
    preconditions:
      - which kubectl
    vars:
      SCALED_OBJECTS:
        sh: kubectl get scaledobjects --all-namespaces --no-headers --output=jsonpath='{range .items[*]}{.metadata.namespace},{.metadata.name}{"\n"}{end}'
    cmds:
      - for: { var: SCALED_OBJECTS, split: "\n" }
        cmd: kubectl --namespace {{splitList "," .ITEM | first}} annotate --field-manager=flux-client-side-apply --overwrite scaledobject {{splitList "," .ITEM | last}} autoscaling.keda.sh/paused=true

  keda-resume:
    desc: Resume all KEDA ScaledObjects across all namespaces
    preconditions:
      - which kubectl
    vars:
      SCALED_OBJECTS:
        sh: kubectl get scaledobjects --all-namespaces --no-headers --output=jsonpath='{range .items[*]}{.metadata.namespace},{.metadata.name}{"\n"}{end}'
    cmds:
      - for: { var: SCALED_OBJECTS, split: "\n" }
        cmd: kubectl --namespace {{splitList "," .ITEM | first}} annotate --field-manager=flux-client-side-apply --overwrite scaledobject {{splitList "," .ITEM | last}} autoscaling.keda.sh/paused-
