---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: minecraft-survival
  namespace: default
spec:
  suspend: false
  interval: 1h
  chart:
    spec:
      chart: minecraft
      version: 5.1.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server-charts
        namespace: flux-system
      interval: 5m
  values:
    replicaCount: 0
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: 2026.1.3@sha256:da84359bd92be3d48f4f64b35a70ba9cd593d23a6fc8f68ccacb72ce4e972c41
    fullnameOverride: minecraft-survival
    strategyType: Recreate
    persistence:
      dataDir:
        enabled: true
        existingClaim: minecraft-survival-datadir
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      runAsNonRoot: true
      fsGroup: 1000
    resources:
      requests:
        memory: 9Gi
        cpu: 500m
      limits:
        memory: 9Gi
    startupProbe:
      enabled: true
    extraEnv:
      ENABLE_AUTOPAUSE: FALSE
      PAPER_CHANNEL: "experimental"
    minecraftServer:
      difficulty: normal
      eula: true
      forceReDownload: true
      gameMode: survival
      icon: https://www.freeiconspng.com/uploads/minecraft-server-icon-23.png
      jvmOpts: "-Xms7168M -Xmx7168M --add-modules=jdk.incubator.vector -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20"
      levelSeed: "1.21-20240629-5"
      maxTickTime: -1
      maxWorldSize: 5999968
      memory: 7168M
      modUrls:
        - https://cdn.modrinth.com/data/hXiIvTyT/versions/SKQwLLoQ/EssentialsX-2.21.0.jar
        # - https://cdn.modrinth.com/data/Lu3KuzdV/versions/llmrc4cl/CoreProtect-22.4.jar
        - https://cdn.modrinth.com/data/18HN6DXd/versions/HIMl6isS/LockedChestsPlugin-1.0.jar
        - https://cdn.modrinth.com/data/Vebnzrzj/versions/cfNN7sys/LuckPerms-Bukkit-5.4.145.jar
      # modrinth:
      #   allowedVersionType: alpha
      #   projects:
      #     # - bluemap
      #     # - discordsrv
      #     # - freezehibernate
      #     # - luckperms
      motd: "mcsv.eviljungle.com\n\u00A76\u00A7lSMPl\u00A7r\u00A7l - \u00A7r\u00A7c\u00A7lSMP\u00A7r\n"
      onlineMode: false
      ops: "billimek"
      overrideServerProperties: true
      pvp: false
      rcon:
        enabled: false
        password: "mc-rcon"
        port: 25575
        serviceType: LoadBalancer
      serviceType: ClusterIP
      spawnProtection: 0
      spigetResources:
        - 102931 # NoChatReports
      type: PAPER
      version: "LATEST"
      worldSaveName: "1.21-20240629-5"
      # TODO: https://github.com/itzg/minecraft-server-charts/pull/253 may have broken this functionality. Will likely need to patch the chart. https://github.com/itzg/minecraft-server-charts/pull/259 may have been only a partial fix.
      # extraPorts:
      #   - name: map
      #     containerPort: 8100
      #     service:
      #       enabled: true
      #       type: ClusterIP
      #       port: 8100
      #     ingress:
      #       enabled: true
      #       ingressClassName: nginx-tailscale
      #       hosts:
      #         - name: mcsv-map.eviljungle.com
      #           path: /
      #       tls:
      #       - hosts:
      #         - mcsv-map.eviljungle.com
