---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: external-proxmox
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/internal: "true"
    external-dns.alpha.kubernetes.io/target: "10.0.6.151"
spec:
  parentRefs:
    - name: tailscale-gateway
      namespace: kube-system
    - name: internal
      namespace: kube-system
  hostnames:
    - proxmox.eviljungle.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: external-proxmox
          port: 8006
---
apiVersion: v1
kind: Service
metadata:
  name: external-proxmox
  namespace: default
spec:
  ports:
    - name: https
      port: 8006
      targetPort: 8006
      appProtocol: https
  type: ExternalName
  externalName: nas.home
---
# BackendTLSPolicy to handle self-signed certificate on Proxmox
apiVersion: gateway.networking.k8s.io/v1alpha3
kind: BackendTLSPolicy
metadata:
  name: external-proxmox-tls
  namespace: default
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: external-proxmox
      sectionName: https
  validation:
    hostname: nas.home
    wellKnownCACertificates: System
  options:
    gateway.envoyproxy.io/insecureSkipVerify: "true"