---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: external-proxmox
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/internal: "true"
    external-dns.alpha.kubernetes.io/target: "10.0.6.151"
spec:
  parentRefs:
    - name: tailscale-gateway
      namespace: kube-system
    - name: internal
      namespace: kube-system
  hostnames:
    - proxmox.eviljungle.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: external-proxmox
          port: 8006
---
apiVersion: v1
kind: Service
metadata:
  name: external-proxmox
  namespace: default
spec:
  ports:
  - name: proxmox
    port: 8006
    targetPort: 8006
    appProtocol: https
  type: ExternalName
  externalName: nas.home