---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: external-minio
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/external: "true"
spec:
  parentRefs:
    - name: tailscale-gateway
      namespace: kube-system
  hostnames:
    - minio-nas.eviljungle.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: external-minio
          port: 9001
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: external-minio-internal
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/internal: "true"
spec:
  parentRefs:
    - name: internal
      namespace: kube-system
  hostnames:
    - minio-nas.eviljungle.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: external-minio
          port: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: external-minio
  namespace: default
spec:
  ports:
  - name: minio
    port: 9001
    targetPort: 9001
  type: ExternalName
  externalName: nas.home