---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: system-monitoring-prometheus-operator-crds
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./example/prometheus-operator-crd
  prune: true
  sourceRef:
    kind: GitRepository
    name: prometheus-operator
    namespace: flux-system
  validation: client
  healthChecks:
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: alertmanagerconfigs.monitoring.coreos.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: alertmanagers.monitoring.coreos.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: podmonitors.monitoring.coreos.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: probes.monitoring.coreos.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: prometheuses.monitoring.coreos.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: prometheusrules.monitoring.coreos.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: servicemonitors.monitoring.coreos.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: thanosrulers.monitoring.coreos.com