helmOperator:
  create: false
git:
  url: "git@github.com:billimek/k8s-gitops"
image:
  repository: fluxcd/flux-prerelease:master-c02b716f
registry:
  rps: 1
  burst: 1
memcached:
  tolerations:
  - key: "arm"
    operator: "Exists"
additionalArgs:
- --connect=ws://fluxcloud
prometheus:
  enabled: true
  serviceMonitor:
    create: false
    interval: 30s
    scrapeTimeout: 10s
    namespace: flux
syncGarbageCollection:
  enabled: true
  dry: false
