---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: booklore-secret
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: booklore-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        booklore_mariadb_password: "{{ .booklore_mariadb_password }}"
        booklore_mariadb_root_password: "{{ .booklore_mariadb_root_password }}"
  dataFrom:
    - extract:
        key: booklore
