---
apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  name: valheim-helm-values
  namespace: default
spec:
  keys:
    - values.yaml
  path: secrets/default/valheim/valheim-helm-values
  type: Opaque
