apiVersion: v1
kind: ConfigMap
metadata:
  name: recyclarr-configmap
  namespace: default
data:
  recyclarr.yml: |
    sonarr:
      sonarr_main:
        base_url: http://sonarr.default.svc.cluster.local:8989
        api_key: !env_var SONARR_API_KEY
        delete_old_custom_formats: true
        media_management:
          propers_and_repacks: do_not_prefer
        media_naming:
          episodes:
            anime: default
            daily: default
            rename: true
            standard: default
          season: default
          series: plex-imdb
        quality_definition:
          type: series
        quality_profiles:
          - trash_id: 72dae194fc92bf828f32cde7744e51a1  # WEB-1080p
            reset_unmatched_scores:
              enabled: true
          - trash_id: d1498e7d189fbe6c7110ceaabb7473e6  # WEB-2160p
            reset_unmatched_scores:
              enabled: true
        custom_format_groups:
          add:
            - trash_id: d776a1ea912a117d66d83b880ff2055d  # [HDR Formats] DV (w/o HDR fallback)
            - trash_id: f4a0410a1df109a66d6e47dcadcce014  # [Optional] Miscellaneous
              select:
                - 32b367365729d530ca1c124a0b180c64  # Bad Dual Groups
                - 82d40da2bc6923f41e14394075dd4b03  # No-RlsGroup
                - e1a997ddb54e3ecbfe06341ad323c458  # Obfuscated
                - 06d66ab109d4d2eddb2794d21526d140  # Retags

    radarr:
      radarr_main:
        base_url: http://radarr.default.svc.cluster.local:7878
        api_key: !env_var RADARR_API_KEY
        delete_old_custom_formats: true
        media_management:
          propers_and_repacks: do_not_prefer
        media_naming:
          folder: plex-imdb
          movie:
            rename: true
            standard: plex-imdb
        quality_definition:
          type: sqp-streaming
        quality_profiles:
          - trash_id: d1d67249d3890e49bc12e275d989a7e9  # HD Bluray + WEB
            reset_unmatched_scores:
              enabled: true
          - trash_id: 5128baeb2b081b72126bc8482b2a86a0  # [SQP] SQP-1 (2160p)
            reset_unmatched_scores:
              enabled: true
        custom_format_groups:
          add:
            - trash_id: 9337080378236ce4c0b183e35790d2a7  # [Optional] Miscellaneous
              select:
                - b6832f586342ef70d9c128d40c07b872  # Bad Dual Groups
                - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5  # No-RlsGroup
                - 7357cf5161efbf8c4d5d0c30b4815ee2  # Obfuscated
                - 5c44f52a8714fdd79bb4d98e2673be1f  # Retags
            - trash_id: f4f1474b963b24cf983455743aa9906c  # [Optional] Movie Versions
              select:
                - 0f12c086e289cf966fa5948eac571f44  # Hybrid
                - 570bc9ebecd92723d2d21500f4be314c  # Remaster
                - eca37840c13c6ef2dd0262b141a5482f  # 4K Remaster
                - e0c07d59beb37348e975a930d5e50319  # Criterion Collection
                - 9d27d9d2181838f76dee150882bdc58c  # Masters of Cinema
                - db9b4c4b53d312a3ca5f1378f6440fc9  # Vinegar Syndrome
                - 09d9dd29a0fc958f9796e65c2a8864b4  # Open Matte
                - eecf3a857724171f968a66cb5719e152  # IMAX
                - 9f6cbff8cfe4ebbc1bde14c7b7bec0de  # IMAX Enhanced
                - 957d0f44b592285f26449575e8b1167e  # Special Edition
                - e9001909a4c88013a359d0b9920d7bea  # Theatrical Cut
            - trash_id: 47f0d69750de9e16855915fa73bb7b08  # [Optional] SDR
              select:
                - 25c12f78430a3a23413652cbd1d48d77  # SDR (no WEBDL)
