---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/prometheusrule_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: volsync
  namespace: kube-system
spec:
  groups:
    - name: volsync.rules
      rules:
        - alert: VolSyncComponentAbsent
          annotations:
            summary: VolSync component has disappeared from Prometheus target discovery.
          expr: |
            absent(up{job="volsync-metrics"})
          for: 15m
          labels:
            severity: critical
        - alert: VolSyncVolumeOutOfSync
          annotations:
            summary: >-
              {{ $labels.obj_namespace }}/{{ $labels.obj_name }} volume
              is out of sync.
          expr: |
            volsync_volume_out_of_sync == 1
          for: 15m
          labels:
            severity: critical
        - alert: KopiaMaintenanceFailure
          annotations:
            summary: Kopia maintenance job has failed.
          expr: |
            kube_job_status_failed{job_name=~"kopia-maint-.*"} > 0
          for: 5m
          labels:
            severity: critical
        - alert: KopiaMaintenanceMissing
          annotations:
            summary: Kopia maintenance has not run in over 8 days.
          expr: |
            (time() - kube_job_status_completion_time{job_name=~"kopia-maint-.*"}) > 691200
          for: 1h
          labels:
            severity: warning
        - alert: KopiaMaintenanceTimeout
          annotations:
            summary: Kopia maintenance job is taking longer than 4 hours.
          expr: |
            kube_job_status_active{job_name=~"kopia-maint-.*"} == 1 and
            (time() - kube_job_status_start_time{job_name=~"kopia-maint-.*"}) > 14400
          for: 15m
          labels:
            severity: warning
