---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/gateway.networking.k8s.io/gateway_v1.json
# Gateway for public/internet DNS records (Cloudflare)
# Routes referencing this gateway will have DNS records pointing to eviljungle.com (router public IP)
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public
  namespace: kube-system
  annotations:
    external-dns.alpha.kubernetes.io/target: "eviljungle.com"
spec:
  gatewayClassName: eg-standard
  infrastructure:
    annotations:
      lbipam.cilium.io/ips: "10.0.6.150"
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.eviljungle.com"
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.eviljungle.com"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: acme-crt-secret
            namespace: cert-manager
    - name: http-bare
      protocol: HTTP
      port: 80
      hostname: "eviljungle.com"
      allowedRoutes:
        namespaces:
          from: All
    - name: https-bare
      protocol: HTTPS
      port: 443
      hostname: "eviljungle.com"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        certificateRefs:
          - kind: Secret
            name: acme-crt-secret
            namespace: cert-manager
